### ISSUE TITLE
Špatné rozvržení v tabulce ekvivalentů

### ISSUE THREAD

**Issue by AsciiWolf** [MikkCZ/proc-linux-cz#42]
Rozšířený seznam [ekvivalentů](https://proc.linux.cz/ekvivalenty/) má špatné rozvržení, viz následující snímek obrazovky:
![seznam_ekvivalentu](https://user-images.githubusercontent.com/2339930/72515001-7f727200-384f-11ea-8d18-40f51188f084.png)

**Comment by MikkCZ** [comment]
Zkusil jsem to zběžně devtools a zřejmě by to vyřešilo pravidlo
```css
.inline-nav ul li {
  margin-right: 1em;
}
```
